image: yardinternet/php7.2-composer

pipelines:
  custom:
    manually:
      - step:
          name: unit test
          caches:
            - composer
            - vendor-directory
          script:
            - composer install --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction

            - ./vendor/bin/phpunit --testsuite "Unit Test Suite"
  branches:
    "{master,develop}":
      - step:
          name: unit test
          caches:
            - composer
            - vendor-directory
          script:
            - composer install --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction
            - ./vendor/bin/phpunit --testsuite "Unit Test Suite"

definitions:
  caches:
    vendor-directory: vendor
